# Configuração Principal do M4Pets
# Desenvolvido por m4nst3in
# Version: 1.0.0

# Configurações gerais
general:
  # Prefixo usado nas mensagens do plugin
  prefix: "&8[&bM4&9Pets&8] "
  
  # Intervalo de salvamento automático dos dados (em minutos)
  save-interval: 5
  
  # Idioma das mensagens (atualmente apenas pt-BR)
  language: "pt-BR"
  
  # Debug mode - mostra mensagens adicionais no console
  debug: false

# Configurações do banco de dados SQLite
database:
  filename: "m4pets.db"
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    max-lifetime: 1800000
    connection-timeout: 30000
    
# Configurações da economia
economy:
  # Custo de ressuscitar um pet (porcentagem do valor original)
  resurrect-cost-percent: 25
  
# Configurações de hologramas
holograms:
  # Altura do holograma em relação ao pet
  height: 1.5
  # Atualização do holograma em ticks
  update-interval: 20
  # Formato do holograma
  format:
    - "&b%pet_name%"
    - "&aHP: &f%pet_health%&7/&f%pet_max_health%"
    - "&eNível: &f%pet_level%"

# Configurações de GUI
gui:
  # Título da GUI principal
  main-title: "&5&l✨ &9&lM4Pets &8&l| &6&l⭐ Menu Principal ⭐"
  
  # Itens da GUI principal
  main-items:
    pet-store:
      material: "CHEST"
      name: "&e&l🛒 &f&lLoja de Pets"
      lore:
        - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
        - "&7🌟 &fDescubra pets incríveis"
        - "&7   &fpara todas as aventuras!"
        - ""
        - "&7⚔️ &fGuerreiros poderosos"
        - "&7🐎 &fMontarias velozes"
        - "&7🔨 &fTrabalhadores úteis &7(em breve)"
        - "&7🌸 &fDecorativos únicos &7(em breve)"
        - ""
        - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
        - "&e&l👆 &6Clique para explorar!"
      slot: 11
    
    my-pets:
      material: "NAME_TAG"
      name: "&a&l🐾 &f&lMeus Pets"
      lore:
        - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
        - "&7💚 &fGerencie seus companheiros"
        - "&7   &ffiéis e suas habilidades!"
        - ""
        - "&7✏️ &fRenomeie seus pets"
        - "&7⚡ &fMelhore suas estatísticas"
        - "&7💎 &fPersonalize com cosméticos"
        - "&7🎨 &fMude suas aparências"
        - ""
        - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
        - "&e&l👆 &6Clique para gerenciar!"
      slot: 15
    
    info:
      material: "BOOK"
      name: "&b&lℹ &f&lInformações"
      lore:
        - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
        - "&7📖 &fApenda tudo sobre"
        - "&7   &fo sistema de pets!"
        - ""
        - "&7🎯 &fComo usar comandos"
        - "&7🎮 &fTipos de pets disponíveis"
        - "&7💡 &fDicas e truques"
        - "&7🛠️ &fSuporte e ajuda"
        - ""
        - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
        - "&e&l👆 &6Clique para aprender!"
      slot: 22
      
  # Configurações da GUI da loja
  store:
    title: "&5&l✨ &9&lM4Pets &8&l| &e&l🛒 Loja de Pets" # Updated title
    
    # Categorias na loja
    categories:
      warrior:
        enabled: true
        material: "DIAMOND_SWORD"
        name: "&c&l⚔ Guerreiros ⚔" # Updated name
        lore:
          - "&7Valentes companheiros de batalha," # Updated lore
          - "&7prontos para defender você!"      # Updated lore
        slot: 10
        implemented: true
        
      mount:
        enabled: true
        material: "SADDLE"
        name: "&6&l🐎 Montarias 🐎" # Updated name
        lore:
          - "&7Explore o mundo com agilidade"  # Updated lore
          - "&7montado em criaturas leais!"     # Updated lore
        slot: 12
        implemented: true
        
      worker:
        enabled: true
        material: "IRON_PICKAXE"
        name: "&e&l🔨 Trabalhadores 🔨" # Updated name
        lore:
          - "&7Aliados incansáveis para suas tarefas," # Updated lore
          - "&7coletando e produzindo por você!"    # Updated lore
          - ""
          - "&e&l✨ EM BREVE! ✨" # Updated "coming soon"
        slot: 14
        implemented: false
        
      decorative:
        enabled: true
        material: "PAINTING"
        name: "&d&l🌸 Decorativos 🌸" # Updated name
        lore:
          - "&7Adicione um toque de charme e estilo" # Updated lore
          - "&7com pets de beleza singular!"        # Updated lore
          - ""
          - "&e&l✨ Descubra benefícios únicos! ✨" # Updated to reflect features
        slot: 16
        implemented: true

# Configuração dos pets
pets:
  # Configurações globais para todos os pets
  global:
    # Tempo de spawn do pet (em segundos)
    spawn-cooldown: 30
    name-update-interval: 10  # Intervalo em ticks para atualizar os nomes das entidades (10 = 0.5 segundos)
    show-health-bar: true     # Mostrar a barra de vida no nome do pet
    show-level: true          # Mostrar o nível no nome do pet
    # Tempo máximo que um pet fica spawned (em minutos, 0 para infinito)
    max-spawn-time: 0
    # Distância máxima que o pet pode ficar do dono (em blocos)
    max-distance: 30
    # Desativar o pet quando o dono se desconecta
    despawn-on-disconnect: true
    # Desativar o pet quando o dono muda de mundo
    despawn-on-world-change: true
    # Nível máximo dos pets
    max-level: 5
    
  # Configurações específicas para pets montaria
  mount:
    horse:
      name: "Cavalo"
      icon: "HORSE_SPAWN_EGG"
      cost: 3000
      base-speed: 0.3
      base-health: 30
      speed-increase-per-level: 0.06
      health-increase-per-level: 7
      level5-ability: "Pulo aumentado (alto)"
      variants:
        - "WHITE"
        - "CREAMY"
        - "CHESTNUT"
        - "BROWN"
        - "BLACK"
        - "GRAY"
        - "DARK_BROWN"
        
    donkey:
      name: "Burro"
      icon: "DONKEY_SPAWN_EGG"
      cost: 2000
      base-speed: 0.25
      base-health: 25
      speed-increase-per-level: 0.04
      health-increase-per-level: 6
      level5-ability: "Pode armazenar itens quando montado"
      variants:
        - "default"
        
    mule:
      name: "Égua"
      icon: "MULE_SPAWN_EGG"
      cost: 2500
      base-speed: 0.28
      base-health: 28
      speed-increase-per-level: 0.05
      health-increase-per-level: 6
      level5-ability: "Pode carregar mais itens quando montada"
      variants:
        - "default"

  # Configurações específicas para pets guerreiros
  warriors:
    zombie:
      name: "Zumbi Guerreiro"
      icon: "ZOMBIE_SPAWN_EGG"
      cost: 4000
      base-health: 40
      base-damage: 8
      health-increase-per-level: 10
      damage-increase-per-level: 2
      level5-ability: "Sede de Sangue - Regenera 2 corações por kill"
      variants:
        - "default"
        - "husk"
        - "drowned"
        
    skeleton:
      name: "Esqueleto Guerreiro"
      icon: "SKELETON_SPAWN_EGG"
      cost: 4500
      base-health: 35
      base-damage: 10
      health-increase-per-level: 8
      damage-increase-per-level: 2.5
      level5-ability: "Rajada Mortal (ranged) / Ataque Giratório (melee)"
      variants:
        - "default"
        - "stray"
        - "wither_skeleton"
        
    vindicator:
      name: "Vindicador Guerreiro"
      icon: "VINDICATOR_SPAWN_EGG"
      cost: 5000
      base-health: 50
      base-damage: 12
      health-increase-per-level: 12
      damage-increase-per-level: 3
      level5-ability: "Fúria Berserker - Dano e velocidade dobrados por 15s"
      variants:
        - "default"
        - "pillager"
        
  # Configurações específicas para pets decorativos
  decorative:
    cat:
      name: "&fGato"
      icon: "CAT_SPAWN_EGG"
      cost: 1200
      base-health: 10
      proximity-radius: 5.0
      variants:
        - "tabby"
        - "siamese"
        - "black"
        - "red"
        - "white"
    parrot:
      name: "&fPapagaio"
      icon: "PARROT_SPAWN_EGG"
      cost: 1500
      base-health: 8
      proximity-radius: 5.0
      variants:
        - "red"
        - "blue"
        - "green"
        - "cyan"
        - "gray"
    rabbit:
      name: "&fCoelho"
      icon: "RABBIT_SPAWN_EGG"
      cost: 1000
      base-health: 6
      proximity-radius: 5.0
      variants:
        - "brown"
        - "white"
        - "black"
        - "splotched"
    axolotl:
      name: "&fAxolote"
      icon: "AXOLOTL_SPAWN_EGG"
      cost: 1800
      base-health: 12
      proximity-radius: 5.0
      variants:
        - "wild"
        - "blue"
        - "gold"
        - "lucy"
    wolf:
      name: "&fLobo"
      material: "BONE"
      cost: 1200.0
      lore:
        - "&7Um companheiro leal e nobre."
        - "&7Concede Força I ao seu dono"
        - "&7quando estiver próximo."
        - ""
        - "&eNível Máximo: &65"
        - "&aCusto: &6%cost%"
      base-health: 25.0
      health-increase-per-level: 6.0
      level5-ability: "&6Força II constante ao dono."
      proximity-radius: 5.0 # Raio para o efeito de Força

# Configurações dos cosméticos
cosmetics:
  particles:
    heart:
      name: "Corações"
      icon: "RED_DYE"
      cost: 500
      particle-type: "HEART"
      
    flame:
      name: "Chamas"
      icon: "BLAZE_POWDER"
      cost: 800
      particle-type: "FLAME"
      
    cloud:
      name: "Nuvens"
      icon: "WHITE_DYE"
      cost: 600
      particle-type: "CLOUD"
      
    note:
      name: "Notas Musicais"
      icon: "NOTE_BLOCK"
      cost: 700
      particle-type: "NOTE"
      
    portal:
      name: "Portal"
      icon: "ENDER_PEARL"
      cost: 1200
      particle-type: "PORTAL"