name: M4Pets
version: 1.0.0
main: me.m4nst3in.m4plugins.M4Pets
api-version: 1.21
authors: [m4nst3in]
description: Sistema de pets completo para servidores Minecraft
website: https://github.com/m4nst3in/m4Pets

softdepend: [Vault, DecentHolograms]

commands:
  pets:
    description: Comando principal do plugin M4Pets
    usage: /pets
    aliases: [pet, m4pets]
    
permissions:
  m4pets.use:
    description: Permite usar o plugin M4Pets
    default: true
  m4pets.admin:
    description: Permite usar comandos administrativos do plugin
    default: op